### ISSUE TITLE
Merging different forks : Discussion

### ISSUE THREAD

**Issue by Daandelange** [Daandelange/ofxImGui#1]
Various improvements from various branches. See the [jvcleave branch](/Daandelange/ofxImGui/tree/jvcleave).
Everything should still be backwards-compatible with older versions of ofxImGui.

- - - - -

From existing forks
-------------------
 - [x] Adds possibility to [set ImGuiConfigFlags](https://github.com/Daandelange/ofxImGui/commit/e31482793ee21a8e2ee17c32e83f0e45bd2b69c9) as a 2nd setup() argument.
 - [x] Arch linux [compilation fix](https://github.com/d3cod3/ofxImGui/commit/8901940c11bed56eb1bd976ebd47fcb596b69644).
 - [x] Added [new imgui colors to default theme](https://github.com/Daandelange/ofxImGui/commit/82d308e2653099f0ddf10afab1b120c764b2f3f4).
 - [x] Implements [support for multiple/shared ofxImGui contexts](https://github.com/Daandelange/ofxImGui/commit/dd5813eae5a2c0695307a9c7acf3ec9c40381ad2). (for handling the case where multiple ofxImGui instances co-exist, more modulable code ) ([related issue](https://github.com/jvcleave/ofxImGui/issues/93)) (to be tested)
 - [x] Adds [font features](https://github.com/Daandelange/ofxImGui/commit/a288774a4ff2bd395a47e7720d9cdb487e23fc94) (doesn't work, to be finished. See [proof of concept in Mosaic](https://github.com/d3cod3/Mosaic/blob/464314ca2da4ec1e743f31bc8d72f30d766b5afa/src/ofApp.cpp#L82-L112))
 - [x] Adds more keyboard key strokes needed by ImGui
 - [x] Add [examples to .gitignore for qt projects](https://github.com/d3cod3/ofxImGui/commit/b91736cd661ab237911ca2d8be7be1d606daa721) + general improvement
 - [x] Adds [Example-multi-window](https://github.com/Daandelange/ofxImGui/commit/46797e4004a277479912cc77274587553d82dea2). (Doesn't work yet, won't work. Current state to be documented with possibilities/explanation)
 - [x] Added ofvec3 to imvec2 cast operators : daandelange@c4c94f4 (because some oF 2d functions return 3d values)

_Note: all above points are almost included in [this commit](https://github.com/Daandelange/ofxImGui/commit/e6f4e4360be0b492f48eb3995851e05497683359), which I used as a starting point for the merge. It's close to current jvcleave/ofxImGui, with the above changes, keeping whitespaces from jvcleave. Imgui versions are both 1.77_WIP aka the docking release._

- - - -

New Stuff
---------
1. **Examples** :
	- [x] Added example-advanced.  
		- [x] Moved oF image loading to it and added combining oF drawing with gui rendering (coordinates example).
		- [x] Add custom theme demo to it.
		- [x] Section about loading imgui plugins.
 	- [x] Adds Example-Multi-Context to demonstrate chaining
 	- [x] Update `example-multiwindow` (as a WIP)
 	- [x] Add a new fonts example.
 	- [x] `example-demo` : Stripped to demo only.
 	- [x] `example-simple` : a minimal ofxImGui setup.
 	- [x] `example-imguizmo` : [example with an ofxImGui plugin](https://github.com/moebiussurfing/ofxImGui/commit/30359aab97f54a4b734b5e398bd94a13908b7643).
 	- [x] Verify/Update all examples for of0.11.
2. **Readme changes** :
 	- [x] New developper section
 	 	- [x] How to update imgui ?
 	 	- [x] Other dev info.
 	- [x] New usage section.
 	- [x] Examples text changed
 	- [x] Document autodraw feature
 	- [x] Add ImGui description, compared to other GUI libraries 
3. **New features**
 	- [x] New shareMode automatic (or manual) setting. (solves having multiple ofxImGui::Gui instances within the same app. Allows multiple addons to use ofxImGui).
 	- [x] Update imgui to use official backends. `- 2018/06/08 (1.62) - examples: the imgui_impl_xxx files have been split to separate platform (Win32, Glfw, SDL2, etc.) from renderer (DX11, OpenGL, Vulkan,  etc.).`
 		- [x] ofxImGui was using a wrapper based on an old imgui example. These have been replaced by backends, recommended wrappers that are maintained by ImGui. Using these wrappers will make updating ImGui easier. This was also the main motivation for [ofxImGuiSimple](https://github.com/PlaymodesStudio/ofxImGuiSimple).
 	 	- [x] ImGui [now asks](https://nullrefer.com/?https://github.com/ocornut/imgui/issues/586#issuecomment-363563645) every API user (your app) to create a context, isolating each process/instance/context from one another. (`ImGui::CreateContext()`)
 	 	- [x] This completely changes the way ofxImGui is implemented. Backends and rendering is now separated from oF; this might impact ofxImGui behaviour. Some details below.
 	 	- [x] Use `OFXIMGUI_ENABLE_OF_BINDINGS` to revert to legacy implementation.
 	 	- [x] Indirectly fixes jvcleave#102 .
 	- [x] Multiwindow alpha. `OFXIMGUI_MULTIWINDOW_IMPL` _See notes below._
 	- [x] Enables loading custom fonts, including font-awesome icons.
 	- [x] Autodraw respects the original behaviour, rendering when calling `gui.end()`, but not in shared mode. *(Note : this is a slightly breaking change, only affecting the rare projects using autodraw, and which enable the new shared mode, and which draw graphics over the GUI : the gui would switch to be rendered above all graphics)*
 	- [x] Polish everything, see lists in posts below.

Multi-Window/Viewport/Context notes
------------------------------------
There's a lot of confusion around multiple viewports, windows and contexts, and most of this is still work in progress. It's useful to read the [ImGui Glossary](https://github.com/ocornut/imgui/wiki/Glossary) for precise definitions of various terms.  
There's a lot of different ways to setup ImGui, and there are different ways to run oF (platform/window manager/number of windows, etc.) As long as there's **1 single oF window**, this is quite obvious, and the new chaining methods make this even more flexible. But **multiple oF windows** makes it more complex. Should the GUI be available in all windows ? If so, should they make one huge UI across multiple windows, or should they each behave independently ? In terms of writing oF applications, the most common scenario would be to have an renderer output window and one or multiple GUI windows, so then you just run ofxImGui in one of them. But that doesn't cover all scenarios.  

Some notes/findings/thoughts on this :
 - Multiple Instances, Contexts, Windows, Viewports. What do we really need ?
	- **ImGui contexts** seems to act as a sandboxing utility to enable using ImGui from different points, acting as a barrier between both. Ensures a binding with a backend for each imgui instance within the same application. Not directly related to rendering, although each instance need a renderer. Seems to be rather for solving multiple imgui instances within the same application. 
	- **ImGui viewports** refers to the feature that allows popping-out gui windows, and to the windows created for that. Also similar: secondary viewports, virtual viewports.
	- **ImGui host viewport** (or main viewport) : Platform/system windows that can host other imgui windows. Currently limited to 1, extra oF windows should be bound to this in the future. Multiple host windows. It will also be possible to use ImGui without host viewport (only popup windows).
	- **OpenGL shared context** : In case of multiple windows, Glfw windows need a special setup allowing imgui to share textures between multiple windows.
 - The current implementation is different from #53, although it implements a part of it.
 This is no real multi context. With chaining enabled, ofxImGui is setup to seamlessly create one context per window, the first caller setting up the ImGui instance.
 - This is also why imgui windows cannot move from 1 glfw window to another one with this solution (example-multiwindow). A better approach could the future **multiple host viewports** implementation. See also [this issue](https://nullrefer.com/?https://github.com/ocornut/imgui/issues/2471). 
 - Depending on the oF context/setup, making Gui::context a singleton (static) can help hook it up (rare cases). Use a single context (multiple windows) or multicontext (singleton) ?
 - ofxImGui legacy : At this point, ofxImGui is about to be empowered, but I guess a lot of users like its simplicity. So now I'm wondering : is this going too far ? Does it make sense upgrading this addon ? Or should this become a clone ? Should there be 2 variants of this plugin : simple & advanced ? This said, there are already a lot of clones around, but they all seem to solve particular use cases... On the other side, without any specific ImGuiConfigFlags on setup(), ofxImGui remains fairly simple and minimal.

#### ofxImGui Muti-window support
The current multi-window implementation is a (working) draft because this has to be finished and tested.  
In my opinion, it's better to wait for ImGui releasing multi-viewport support in combination with directions from [this comment](https://nullrefer.com/?https://github.com/ocornut/imgui/issues/3012#issuecomment-614485223) to share GLFW window context.
At the moment, it works with GLFW windows, only when they have the same size. (otherwise there are mouse coordinate problems). Not recommended to use.

Wrapper / Engine / Backend notes
------------------------------------
This update changes how the GLFW wrapper is interfaced with oF. `BaseEngine` and `EngineGLFW` have less importance. However, the engine wrapper logic is close to oF, so I kept bits of it instead of removing it like other implementations. Also it will facilitate implementing the font features.
These backends also use their own glfw event listeners, so I have commented the ofListeners. As ImGui is getting complex, using the backend way looks the most future-proof, while getting the most out of imgui. I've left most of the previous code, it's probably broken, but it can be enabled with `OFXIMGUI_ENABLE_OF_BINDINGS`.
This changes ofxImGui behaviour a lot, because previously used functions (`programmableDrawData()`, `createDeviceObjects()`, etc.) are now handled by the new imgui backends, without any oF related calls.

To reflect these changes, there's also new methods : `BaseEngine::NewFrame/EndFrame` so that they better reflect the Imgui API. Also, `Gui::render()` (internal) is now separated from `Gui::draw()` so rendering is more flexible (handle autoDraw and chaining...). And `BaseEngine::draw()` has been renamed to `render()` and simply renders without looking at the config.

The Gui class orchestrates binding with OF and imgui rendering. Depending the `setup()` configuration, it calls the correct `BaseEngine*` calls when needed.

Depreciation note : [`io.RenderDrawListsFn is depreciated since 1.60 and will be removed in ±2.0`](https://nullrefer.com/?https://github.com/ocornut/imgui/issues/1599)

Notes on oF + GLFW
------------------
The current ImGui backend is not seamlessly compatible with oF's libGLFW. oF0.11.0 uses a pre-3.3 version, which misses a function used by imGui.
 - Downgrade GLFW to 3.3.0 ([ofTheo/glfw](https://github.com/ofTheo/glfw), used by oF's `download_libs.sh`)
 ````bash
# If you don't have apothecary
cd OF/scripts && git clone https://github.com/openframeworks/apothecary.git
# Edit ./apothecary/apothecary/formulas/glfw.sh, change to `VER=3.3-stable GIT_URL=https://github.com/ofTheo/glfw.git`
 # Update
 ./apothecary/apothecary/apothecary -t osx -j 4 update glfw
 # Copy ./apothecary/glfw to OF/libs/
 ./apothecary/apothecary/apothecary -t osx -j 4 copy glfw
 ````
 - Alternatively, you can open imgui_impl_glfw.cpp and change `3300` to `3400` on the line defining `GLFW_HAS_MONITOR_WORK_AREA` to disable the missing feature and more.
 
 Note: **GLWF 3.4.0** will bring lots of imgui interface improvements (more mouse cursors, better viewports handling, etc.).

-----

I'll update this 1st post as things advance.

**Comment by Daandelange** [comment]
Just had some time to continue this.
 - GLWF implementation is getting there. (others remain to be implemented/tested)
 - Font loading is now also supported.
 - The "chaining" option is now removed as an argument, and detected automatically during setup.

**Comment by Daandelange** [comment]
I've added some more examples, updated others. This is starting to look good. :)

I've been able to test in linux_64, iOS-simulator, and extensively for osx. I'll check Rpi later.
Windows, iOS (real-device) and Vulkan, I'm not able to test.

**Comment by Daandelange** [comment]
Rpi compatibility checked !

Last stuff to do :
- [x] Update all examples for Rpi (on the way).
- [ ] Test / Fix imgui window restore behaviour together with `imgui.ini` usage. See https://github.com/Daandelange/ofxImGui/issues/3#issuecomment-776314247 and [this problematic code](https://github.com/Daandelange/ofxImGui/blob/678284196895b28b29face9ab9d1f68444ea30ac/src/ImHelpers.cpp#L95-L97).
- [x] Update/add some examples with @moebiussurfing's code samples. 
- [x] Improve the autodraw feature to always draw after `ofApp::Draw()` rather than on `gui.end()`. See https://github.com/Daandelange/ofxImGui/issues/2#issuecomment-761760307
- [x] Update `readme.md` with relevant information (compatibility). Split dev info to `developpers.md` ? Add `Changelog.md` ?

**Comment by moebiussurfing** [comment]
hey Daan, I just found a very little "Bug", not important, but dunno if it
can affect other things, but just in case:

when using the VS2017 extension to add addons, I get an error when
compiling the added ofxImGui...
This do not happens when using the official Project Generator (and in
official ofxImGui I think)

[image: ImGui_addonVS2017.PNG]

**Comment by Daandelange** [comment]
Hey, Yes, some project flags need to be set so the addon compiles correctly, I guess the vs extension doesn't parse `addons.mk` (?). (I cannot see your image)
Good point to clarify/improve/document this.

For now, some flags are set here : in [`addon_config.mk`](https://github.com/Daandelange/ofxImGui/blob/jvcleave/addon_config.mk)
The imgui backend flags could probably be checked and defaulted in `imconfig.h`.
For the Vulkan file exclusion, adding some preprocessor conditions so that it doesn't fail when being included.

**Comment by moebiussurfing** [comment]
the openframeworks vs extension can add (more) ofxAddons to an "empty"
project.
addons.make can be empty before use the extension.
and addons.make is written/update after this.
it's the same that the old Xcode addon to add ofxAddons on macOS...
So, it looks the VS extension is not reading the addon_config.mk... as you
said
